name: safmobile_portal
description: "Web Apps that customers can manage their services order and make online payments on e-invoice on the go."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  flex_color_scheme: ^8.2.0
  go_transitions: ^0.8.0
  flutter_material_design_icons: ^1.1.7447
  skeletonizer: ^2.0.1
  animations: ^2.0.11
  flutter_staggered_animations: ^1.1.1
  easy_stepper: ^0.8.5+1
  material_segmented_control: ^5.0.1
  timelines_plus: ^1.0.6
  lottie: ^3.3.1

  # State Management
  go_router: ^14.8.1
  provider: ^6.1.4

  # Data Handling
  shared_preferences: ^2.5.3
  intl: ^0.20.0
  jiffy: ^6.3.2
  file_saver: ^0.2.14
  pdf: ^3.11.3
  number_to_words_english: ^2.1.1
  universal_html: ^2.2.4
  qr_code_scanner_plus: ^2.0.10+1
  url_launcher: ^6.3.1

  # Firebase & API
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  http: ^1.3.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  package_rename: ^1.9.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5

flutter_native_splash:
  color: "#fcfcff"
  color_dark: "#1a1c1e"
  image: "assets/icons/launcher_icon.png"
  image_dark: "assets/icons/launcher_icon.png"
  android: true
  ios: true
  web: true
  android_12:
    image: "assets/icons/launcher_icon.png"
    icon_background_color: "#38a4dd"
    image_dark: "assets/icons/launcher_icon.png"
    icon_background_color_dark: "#38a4dd"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.png"
  adaptive_icon_background: "assets/icons/launcher_icon_background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icons/launcher_icon_foreground.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground_inset: 16 # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/icons/launcher_icon_foreground.png" # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/launcher_icon.png"
    background_color: "#38a4dd"
    theme_color: "#006595"
  windows:
    generate: true
    image_path: "assets/icons/launcher_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/launcher_icon.png"

package_rename_config:
  android:
    app_name: Saf Mobile Portal
    package_name: my.safmobile.portal
    override_old_package: com.example.safmobile_portal
    lang: kotlin

  ios:
    app_name: Saf Mobile Portal
    bundle_name: Saf Mobile Portal
    package_name: my.safmobile.portal

  web:
    app_name: Saf Mobile Portal
    description: Saf Mobile Portal is a web app that customers can manage their services order and make online payments on e-invoice on the go.

  linux:
    app_name: Saf Mobile Portal
    package_name: my.safmobile.portal
    exe_name: saf-mobile-portal

  windows:
    app_name: Saf Mobile Portal
    organization: Assaff Enterprise
    copyright_notice: Copyright ©️ 2025 Assaff Enterprise. All rights reserved.
    exe_name: safmobile-portal

  macos:
    app_name: Saf Mobile Portal
    package_name: my.safmobile.portal
    copyright_notice: Copyright ©️ 2025 Assaff Enterprise. All rights reserved.

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
  #   - images/a_dot_ham.jpeg
