name: safmobile_portal
description: "Web Apps that customers can manage their services order and make online payments on e-invoice on the go."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  flex_color_scheme: ^8.2.0

  # State Management
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
