// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkjXZd2cTyZ0xuKq7hS7CSyJZQg_5XD9Y',
    appId: '1:168025117104:web:7b6c378bf685df63c44675',
    messagingSenderId: '168025117104',
    projectId: 'safmobile-database',
    authDomain: 'safmobile-database.firebaseapp.com',
    storageBucket: 'safmobile-database.appspot.com',
    measurementId: 'G-DPDX5QYBYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-K1i7OPWEDcf7d0_YlhFO2YQJK2t0K6Y',
    appId: '1:168025117104:android:3adf1aaf3f9b93f9c44675',
    messagingSenderId: '168025117104',
    projectId: 'safmobile-database',
    storageBucket: 'safmobile-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl-HDrGsmQRVi8pm6xEb5PxjCr5Uwy4K8',
    appId: '1:168025117104:ios:c4f49d92a0b3a59dc44675',
    messagingSenderId: '168025117104',
    projectId: 'safmobile-database',
    storageBucket: 'safmobile-database.appspot.com',
    iosBundleId: 'my.safmobile.portal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl-HDrGsmQRVi8pm6xEb5PxjCr5Uwy4K8',
    appId: '1:168025117104:ios:c4f49d92a0b3a59dc44675',
    messagingSenderId: '168025117104',
    projectId: 'safmobile-database',
    storageBucket: 'safmobile-database.appspot.com',
    iosBundleId: 'my.safmobile.portal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkjXZd2cTyZ0xuKq7hS7CSyJZQg_5XD9Y',
    appId: '1:168025117104:web:7b6c378bf685df63c44675',
    messagingSenderId: '168025117104',
    projectId: 'safmobile-database',
    authDomain: 'safmobile-database.firebaseapp.com',
    storageBucket: 'safmobile-database.appspot.com',
    measurementId: 'G-DPDX5QYBYN',
  );
}
